version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fleetfox-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - fleetfox-network

  nginx:
    image: nginx:alpine
    container_name: fleetfox-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - fleetfox-network
    depends_on:
      - app

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fleetfox-queue
    restart: unless-stopped
    working_dir: /var/www
    command: php artisan queue:work --tries=3
    volumes:
      - ./:/var/www
    networks:
      - fleetfox-network
    depends_on:
      - app

networks:
  fleetfox-network:
    driver: bridge
